// <auto-generated />
namespace ofis_ici_yemek_secim_sistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddFoodImagePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFoodImagePath));
        
        string IMigrationMetadata.Id
        {
            get { return "202607220934124_AddFoodImagePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
